---
title: "Section 6: Mapping"
format: html
---

## Section 6.2

```{r}
library(tidyverse)

active <- read_csv("https://raw.githubusercontent.com/iramler/stlawu_covid/main/slc_towns_active_cases.csv", n_max = 34)
tcases <- read_csv("https://raw.githubusercontent.com/iramler/stlawu_covid/main/slc_towns_total_cases.csv", n_max = 34)

active_long <- active |> pivot_longer(5:ncol(active), names_to = "date",
                                       values_to = "cases")
## repeat for total cases
tcases_long <- tcases |> pivot_longer(5:ncol(tcases), names_to = "date",
                                       values_to = "cases")

library(lubridate)
covid_df <- left_join(tcases_long, active_long,
                      by = c("date", "Order", "NAME")) |>
  mutate(date = mdy(date)) |>
  rename(total_cases = cases.x,
         active_cases = cases.y) |>
  mutate(total_cases = if_else(is.na(total_cases),
                               true = 0, false = total_cases),
         active_cases = if_else(is.na(active_cases),
                                      true = 0, false = active_cases))
  

covid_SLC <- covid_df |> filter(NAME == "St. Lawrence County")
covid_sub <- covid_df |> filter(NAME != "St. Lawrence County")
covid_SLC
covid_sub
ggplot(data = covid_SLC, aes(date, y = active_cases)) +
  geom_line() +
  theme_minimal()
```

```{r}
library(sf)
shp <- read_sf("data/SLC_Civil_Boundaries_SHP/slc.shp") |>
  st_transform(st_crs("+proj=longlat"))
shp
## POLYGON because this is polygonal county data
## Bounding Box: If you drew a recatnagle with these coordinates, it would contain SLC
## CRS = coordinate reference system = longitude/latitude

## geometry contains a bunch of x y coordinates that correspond to 
## vertices of a particular county

covid_sub ## need to join this with shapefile by sub-country NAME
ggplot(data = shp) +
  geom_sf() +
  theme_void()

full_df <- left_join(shp, covid_sub, by = "NAME") |>
  filter(date == max(date)) 

ggplot(data = full_df) +
  geom_sf(aes(fill = active_cases)) +
  theme_void() +
  scale_fill_viridis_c() +
  geom_sf_text(aes(label = active_cases))
```

2020 Election Example:

```{r}
load(here::here("data/election_2020.rda"))
election_2020

ggplot(data = election_2020) +
  geom_sf(aes(fill = per_gop)) +
  theme_void() +
  scale_fill_distiller(type = "seq", palette = "Reds",
                       direction = 1)
```


```{r}
load(here::here("data/ozone.rda"))
ozone

ggplot(data = ozone, aes(x = lon, y = lat)) +
  geom_point(aes(colour = ozone)) +
  coord_fixed() +
  theme_void() +
  scale_colour_viridis_c()
## tigris can be used to plot state boundaries

## comparing average ozone measurements from the two sources would be harder to see with a map (easier to see with boxplots or faceted histogram)
```

```{r}
baseball_soto <- read_csv("data/baseball_soto25.csv") |>
  relocate(plate_x, plate_z, type, pitch_type)
baseball_soto

ggplot(data = baseball_soto, aes(x = plate_x, y = plate_z)) +
  geom_point(aes(colour = type)) +
  scale_colour_viridis_d() +
  theme_minimal() +
  geom_vline(xintercept = -0.83333, linetype = "dashed") +
  geom_vline(xintercept = 0.833333, linetype = "dashed") +
  facet_wrap(~ pitch_type) +
  coord_fixed()
## can also do geom_hline() for other pieces
```

## Section 6.4

```{r}
library(tidyverse)
library(here)
hpi_df <- read_csv(here("data/hpi-tidy.csv")) |>
  mutate(Country = if_else(Country == "United States of America",
                           true = "USA",
                           false = Country))

world_map <- map_data("world")

world_joined <- left_join(world_map, hpi_df, join_by(region == Country))

ggplot(data = world_joined, aes(x = long, y = lat,
                             group = group)) +
  geom_polygon(aes(fill = Footprint)) +
  coord_map(projection = "gilbert") +
  scale_fill_viridis_c() +
  xlim(c(-180, 180))
``` 

