---
title: "Logistic Regression Visualization"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

```{r}
library(tidyverse)
library(here)
library(broom)
theme_set(theme_minimal())

titanic_df <- read_csv(here("data/titanic.csv"),
                       col_types = list(Pclass = col_factor())) |>
  mutate(Pclass = fct_recode(Pclass,
                             "1st" = "1",
                             "2nd" = "2",
                             "3rd" = "3"))
titanic_df

titanic_mod <- glm(Survived ~ Age,
                   data = titanic_df, family = "binomial")
titanic_mod

ggplot(data = titanic_df, aes(x = Age, y = Survived)) +
  geom_jitter(height = 0.05) +
  geom_smooth(method = "glm", method.args = list(family = "binomial")) +
  theme_minimal()

titanic_mod |> tidy()

## exercise 2
titanic_sex <- glm(Survived ~ Sex,
                   data = titanic_df, family = "binomial")
titanic_sex |> tidy()
```

Warm Up Exercise

```{r}
rug_survive <- titanic_df |> filter(Survived == 1)
rug_died <- titanic_df |> filter(Survived == 0)
ggplot(data = titanic_df, aes(x = Age, y = Survived)) +
  geom_rug(data = rug_survive, sides = "t", alpha = 0.3) +
  geom_rug(data = rug_died, sides = "b", alpha = 0.3) +
  geom_smooth(method = "glm",
              method.args = list(family = "binomial")) +
  theme_minimal()
```

```{r}
titanic_large <- glm(Survived ~ Age + Sex + Pclass, data = titanic_df,
                     family = "binomial")
titanic_large |> tidy()

library(modelr)
grid <- titanic_df |>
  data_grid(
    Age = seq_range(Age, n = 10),
    Sex = c("female", "male"),
    Pclass = c("1st", "2nd", "3rd")
  ) 
grid

aug_surv <- augment(titanic_large, newdata = grid,
                    se_fit = TRUE)
aug_surv
```

Exercise 1. The .fitted values are the predicted log odds, which are from negative infinity to positive negative.

Exercise 2.

```{r}
ggplot(data = aug_surv, aes(x = Age, y = .fitted)) +
  geom_line(aes(colour = Sex), linewidth = 1.7) +
  facet_wrap(~ Pclass) +
  scale_colour_viridis_d() +
  geom_rug(data = rug_survive, sides = "t", alpha = 0.3,
           aes(y = Survived)) +
  geom_rug(data = rug_died, sides = "b", alpha = 0.3,
           aes(y = Survived))

## exercise 3 and 4
aug_surv <- aug_surv |>
  mutate(.predprob = exp(.fitted) / (1 + exp(.fitted)))

ggplot(data = aug_surv, aes(x = Age, y = .predprob)) +
  geom_line(aes(colour = Sex), linewidth = 1.7) +
  facet_wrap(~ Pclass) +
  scale_colour_viridis_d() +
  geom_rug(data = rug_survive, sides = "t", alpha = 0.3,
           aes(y = Survived)) +
  geom_rug(data = rug_died, sides = "b", alpha = 0.3,
           aes(y = Survived))
```

Your Turn

```{r}
titanic_int <- glm(Survived ~ Age + Sex + Pclass + Sex:Pclass,
                   data = titanic_df,
                   family = "binomial")

aug_int <- augment(titanic_int, newdata = grid,
                    se_fit = TRUE)

titanic_plot <- bind_rows(lst(aug_surv, aug_int), .id = "model")
titanic_plot <- titanic_plot |>
  mutate(.predprob = exp(.fitted) / (1 + exp(.fitted)))

ggplot(titanic_plot, aes(x = Age, y = .predprob)) +
  geom_line(aes(colour = model), linewidth = 1.7) +
  facet_grid(Sex ~ Pclass) +
  scale_colour_viridis_d() +
  geom_rug(data = rug_survive, sides = "t", alpha = 0.3,
           aes(y = Survived)) +
  geom_rug(data = rug_died, sides = "b", alpha = 0.3,
           aes(y = Survived))

## exercise 4
titanic_int |> glance()
titanic_large |> glance()
## the model with the interaction is the better fit: it
## has a lower BIC and a lower AIC.
```