---
title: "Interactivity Introduction"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## `plotly`

```{r}
library(plotly)
library(tidyverse)

hpi_df <- read_csv(here::here("data/hpi-tidy.csv"))
ggplot(data = hpi_df, aes(x = Footprint, y = Wellbeing)) +
  geom_point() +
  theme_minimal()

plot1 <- ggplot(data = hpi_df, aes(x = Footprint, y = Wellbeing)) +
  geom_point() +
  theme_minimal()

ggplotly(plot1)
```

```{r}
plot1 <- ggplot(data = hpi_df, aes(x = Footprint, y = Wellbeing,
                                   label = Country,
                                   label2 = Region)) +
  geom_point() +
  theme_minimal()

ggplotly(plot1, tooltip = c("label", "label2"))
```

Exercise 1.

```{r}
library(palmerpenguins)
penguin_plot <- ggplot(data = penguins,
                       aes(x = species)) +
  geom_bar(colour = "dodgerblue4", fill = "dodgerblue1")
ggplotly(penguin_plot)
```

Exercise 2.

See 05-ds234.qmd

Your Turn

Advantages

* can be more engaging for the user if they are interacting
* can potentially see more information

Disadvantages

* can be harder to create and/or share
* __harder to convey a particular message__