---
title: "Quiz 2 Take Home"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

"All work presented is my own, and I have followed all rules for collaboration." - Matt Higham

```{r}
library(tidyverse)
library(readxl)
df <- read_excel("data/slu_graduates_17_21.xlsx")

## fixes error in the data
df <- df %>%
  mutate(across(everything(),
                           .fns = ~replace(., . ==  "STATS" , "STAT")))
df %>% filter(major1 == "STAT" | major2 == "STAT" | major3 == "STAT") %>%
  pivot_longer(c(3, 4, 5, 6, 7, 8),
               values_to = "discipline",
               names_to = "type") %>%
  filter(type == "major1" | type == "major2" | type == "major3") %>%
  filter(discipline != "STAT" & !is.na(discipline))

df_stat <- df %>% pivot_longer(c(3, 4, 5, 6, 7, 8),
               values_to = "discipline",
               names_to = "type") %>%
  filter(discipline == "STAT")
semi_join(df, df_stat, by = "adm_id")
```

## Question 2

```{r}
df %>%
  pivot_longer(c(3, 4, 5, 6, 7, 8),
               values_to = "discipline",
               names_to = "type") %>%
  filter(type == "major1" | type == "major2" | type == "major3") %>%
  filter(!is.na(discipline)) %>%
  group_by(sex, discipline) %>%
  summarise(nstudents = n()) %>%
  ungroup() %>%
  group_by(discipline) %>%
  mutate(ntotal = sum(nstudents))
```

```{r}
library(tidyverse)
library(readxl)
df <- read_excel("data/slu_graduates_17_21.xlsx")
## fixes error in the data
df <- df %>% mutate(across(everything(),
                           .fns = ~replace(., . ==  "STATS" , "STAT")))

df_long <- df %>% pivot_longer(3:8, names_to = "type", values_to = "discipline")
df_major <- df_long %>% 
  filter(type == "major1" | type == "major2" | type == "major3")
df_stat <- df_major %>% filter(discipline == "STAT") 
df_statfull <- semi_join(df_long, df_stat, by = "adm_id") %>%
  filter(type == "major1" | type == "major2" | type == "major3")

df_nostat <- df_statfull %>% filter(discipline != "STAT" &
                              !is.na(discipline)) %>%
  group_by(discipline) %>%
  summarise(nstudent = n()) %>%
  mutate(discipline = fct_reorder(discipline, nstudent))
ggplot(data = df_nostat, aes(x = discipline, y = nstudent)) +
  geom_col() +
  coord_flip()
```

2. (8 points)

```{r}
df_major <- df_major %>% filter(!is.na(discipline))
df_sex <- df_major %>% group_by(discipline, sex) %>%
  summarise(nstudent = n()) %>%
  ungroup() %>%
  group_by(discipline) %>%
  mutate(ntotal = sum(nstudent)) %>%
  filter(ntotal >= 50) %>%
  mutate(prop_female = nstudent / ntotal) %>%
  filter(sex == "F") %>%
  arrange(prop_female) %>%
  ungroup() %>%
  mutate(discipline = fct_reorder(discipline, prop_female))

df_sex <- df_sex %>%
  mutate(higher = if_else(prop_female > 0.5,
                                   true = "Female",
                                   false = "Male"))
ggplot(data = df_sex, aes(x = discipline, y = prop_female,
                          colour = higher)) +
  geom_point() +
  geom_segment(aes(y = 0.5, yend = prop_female, x = discipline, xend = discipline)) +
  labs(y = "Proportion of Female Majors in Past 5 Years") +
  coord_flip() +
  theme(legend.position = "none")
  
```
